name: build

on:
  push:
  pull_request:
  release:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "ubuntu-latest-gcc",
            os: ubuntu-latest,
            build_type: "Release",
          }

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Install dependencies
        run: |
          cat /etc/issue
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            cmake \
            libsdl1.2-dev \
            libsdl2-dev
          ninja --version
          cmake --version
          gcc --version
      - name: Configure
        shell: bash
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir \
            -DWARNINGS=ON \
            -DWERROR=ON
      - name: Build
        shell: bash
        run: |
          make VERBOSE=1

# EOF #
